### ISSUE TITLE
[功能]: 设计稿可以本地下载(本地保存)

### ISSUE THREAD

**Issue by loverto** [gongph/fabricjs-studio#1]
类似下图中的本地保存功能

![image](https://user-images.githubusercontent.com/3992018/58749646-0b02e280-84bb-11e9-9bb9-e2b876f2e01f.png)

**Comment by loverto** [comment]
下载功能已经完成，但是下载的尺寸不正确，
建议

1. 把下载放在预览页面，预览页面把尺寸调整为全尺寸，不在是设计时的一半的尺寸
2. 在预览页面提交最终设计稿到服务器端

**Comment by gongph** [comment]
一个问题一个 issues 吧，这样好关闭问题和关联提交记录

**Comment by loverto** [comment]
good
