### ISSUE TITLE
[功能]： 除了提交按钮外，应该还有一个是设计完毕的按钮（用来标志设计完毕）

### ISSUE THREAD

**Issue by loverto** [gongph/fabricjs-studio#14]
![image](https://user-images.githubusercontent.com/3992018/58927880-eccf0800-8782-11e9-9c35-0537fbcb730b.png)

**Comment by gongph** [comment]
设计完毕的按钮 有啥用呢？ 用户接下来要干嘛呢？

**Comment by loverto** [comment]
设计完毕，后用户无法再继续设计该定制信息，只能查看，并且把保存的图片地址设置到定制信息中，方便回显
