### ISSUE TITLE
[问题]： 前台系统更换字体，字体不会立即不生效

### ISSUE THREAD

**Issue by loverto** [gongph/fabricjs-studio#48]

**Comment by loverto** [comment]
测试字体时，记得重启浏览器

**Comment by loverto** [comment]
操作系统： mac 
版本：Catalina Beta
浏览器： chrome
版本： 75.0.3770.100
字体未生效
所有字都是等宽的
![image](https://user-images.githubusercontent.com/3992018/59809384-df914c00-9332-11e9-845d-03f93f7602d6.png)

**Comment by loverto** [comment]
生效的浏览器
操作系统： mac
版本：Catalina Beta
浏览器： Firefox
版本： 68.0b9 
字体生效
![image](https://user-images.githubusercontent.com/3992018/59809368-cb4d4f00-9332-11e9-88e6-ceb4316d517f.png)

**Comment by loverto** [comment]
半生效浏览器
操作系统： mac
版本：Catalina Beta
浏览器： Safari
版本： 13.0 (15608.1.27.40.1)
字体未全部生效
只有微软雅黑和楷体两种字体
![image](https://user-images.githubusercontent.com/3992018/59809307-993bed00-9332-11e9-842a-efed5334493b.png)

**Comment by gongph** [comment]
.ttf 格式的字体浏览器应该全兼容的

**Comment by loverto** [comment]
这个字就是ttf格式的

**Comment by loverto** [comment]
操作系统 window
版本 10
浏览器：chrome 
版本 74.0.3729.169
