### ISSUE TITLE
[问题]: 设计稿本地保存和提交服务器的图片比刀模图的尺寸小了一半

### ISSUE THREAD

**Issue by loverto** [gongph/fabricjs-studio#9]
设计稿本地保存和提交服务器的图片比刀模图的尺寸小了一半

**Comment by gongph** [comment]
@loverto 问题已修复，参考这个 [d96ce9b](https://github.com/gongph/fabricjs-studio/blob/d96ce9ba94feb6246586e3a67fa984eec54efaca/src/views/Studio.vue#L657)
